targets:
  $default:
    builders:
      swagger_dart_code_generator:swagger_dart_code_generator:
        options:
          input_folder: 'lib/generated_code/swaggers'
          output_folder: 'lib/generated_code/api_spec/'