name: be_aware_android
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  camera: ^0.10.5+5
  chopper: ^6.1.4
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  flutter_map: ^6.0.0
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.1.0
  get_it: ^7.6.4
  go_router: ^11.1.4
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  provider: ^6.1.1
  toastification: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^2.12.2

flutter:
  uses-material-design: true
